sudo: enabled
services:
    - docker
before_script:
    - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
script:
    - docker build -t rakudo-star ./$VERSION/$VARIANT

env:
    - VERSION='2021.04' VARIANT='buster'
    - VERSION='2021.04' VARIANT='alpine3.13'
    - VERSION='2022.04' VARIANT='alpine3.13'
    - VERSION='2022.04' VARIANT='alpine3.16'
